#!/bin/bash

# path to ffmpeg
cd $FFMPEG_LOCAL_PATH

# xrectsel from https://github.com/lolilolicon/xrectsel
# get coordinates of the recorded region
ARGUMENTS=$(/usr/local/xrectsel/xrectsel "-s %wx%h -i :0.0+%x,%y") || exit -1

# encode capture lossless
./ffmpeg -f x11grab -r 60 ${ARGUMENTS} -c:v huffyuv -threads 0 tmp.mkv

# transcode capture
./ffmpeg -y -i tmp.mkv -threads 0 -c:v libvpx -quality best -qmin 0 -qmax 0 tmp.webm

echo "video name: "
read -r NOM

mv tmp.webm ${NOM}.webm

# upload sur le serveur (/Bureau/web/webm/ est monté over sshfs https://wiki.archlinux.org/index.php/Sshfs )
# substituable avec un envoie par ftp ou scp
mv ${NOM}.webm $OUT_PATH

# put the out url to copyboard
printf "http://webm.hadjiszs.fr/%s.webm" ${NOM} | xclip -i

rm /tmp/frame*
